# Generated by Django 4.2.7 on 2023-12-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('GameName', models.CharField(max_length=500)),
                ('GameImage', models.URLField(blank=True, null=True)),
                ('GameRating', models.IntegerField(blank=True, null=True)),
                ('GamePrice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
