# Generated by Django 4.2.7 on 2023-12-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamingClientApp', '0002_cartinfo_alter_gameinfo_gamerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='User',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
